### ISSUE TITLE
model.js enhancement

### ISSUE THREAD

**Issue by bdt-taldo** [yacy/yacy_webclient_bootstrap#1]
it would be quite nice to enhance js/setup.js a bit:

- http:// or https:// should be added as protocol
- yacysearch.json as target script is in our case yacysearch.php

Instead of hard-coding this in js/model.js, i'd suggest to have these two settings located in the setup file

**Comment by Orbiter** [comment]
fixed with https://github.com/yacy/yacy_webclient_bootstrap/commit/7e3712315fb495ab3ccbfcb344a00d9b46fec27d
