### ISSUE TITLE
File not found - ViewImage

### ISSUE THREAD

**Issue by bdt-taldo** [yacy/yacy_webclient_bootstrap#2]
FireBug Console reported:
yacy_webclient_bootstrap/yacysearch/ViewImage.png?width=16&height=16&code=TVjBS7vEpMVZ&isStatic=true

ViewImage.png is referenced in js/model.js:139, however it seems to be missing in the repository

**Comment by Orbiter** [comment]
fixed with https://github.com/yacy/yacy_webclient_bootstrap/commit/3b2dfb753438d59675fd58fa412138d286151951
