### ISSUE TITLE
File not found - external.png

### ISSUE THREAD

**Issue by bdt-taldo** [yacy/yacy_webclient_bootstrap#3]
css/base.css:90:  background: url(/env/grafics/external.png) center right no-repeat;

The referenced imgae is not part of the repository; additionally the given path is not part of the repo as well; i'd suggest a relative path, if possible

**Comment by Orbiter** [comment]
fixed in https://github.com/yacy/yacy_webclient_bootstrap/commit/78676ba982aa9940fc17104941f2941e4a105ccd
