### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by bdt-taldo** [yacy/yacy_webclient_bootstrap#5]
upon receiving the landing page (without any arguments passed):

File does not exist: /var/www/yacit01/yacy_webclient_bootstrap/navigation.js, referer: https://localhost:2443/yacy_webclient_bootstrap/

in index.html:29:	<script src="navigation.js" type="text/javascript"></script>
the file is referenced; i found the file in the subdir yacysearch/

<script src="yacysearch/navigation.js" type="text/javascript"></script> would do it; however i'm not sure if navigation.js is already required over there

**Comment by Orbiter** [comment]
fixed in latest commit
