### ISSUE TITLE
IE10 - strange behaviour

### ISSUE THREAD

**Issue by bdt-taldo** [yacy/yacy_webclient_bootstrap#6]
All day long, i had no trouble using the new bootstrap webclient. Suddenly, i got 

"Script600: unknown runtime error" in yacysearch/index,html, line 204 

For me, it seems to be an old IE bug when using innerHTML, as its described for old versions of IE over here: http://stackoverflow.com/questions/5618742/ie-8-and-7-bug-when-dynamically-adding-a-stylesheet

Customer is running an IE10, which issued the above reported error. Due to customer settings, the page is rendered using compatibility mode (but still showing it as compatibility mode IE 10).

If I change this to compatibility mode, but IE9, it's back working; changing to versions 7 or 8 cause the same error message

This leads to no ajax call being submitted and therefore no results shown.

As i didn't change anything besides js/setup.js and the urlRoot in js/model.js i have no clue what might have caused the default compatibility mode to be changed during the day.

I don't think that we need anything below IE 10 to work in this case.

**Comment by Orbiter** [comment]
this looks like to be very difficult to reproduce.

**Comment by Orbiter** [comment]
first try to fix this: all innerHTML in /index.html had been removed. Please test with https://github.com/yacy/yacy_webclient_bootstrap/commit/e990f6670312e08eb8d0fb2fafd95c4b505aa420 and reopen if problem persist.
